# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pics/None/no-img.jpg', upload_to='pics/')),
                ('name', models.CharField(max_length=200)),
                ('build_progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='parent_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgupldr.ImageSet'),
        ),
    ]
